apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-snuba-outcomes-consumer
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "17"
  {{- end }}
{{- define "snuba.outcomesConsumer.container" -}}
command:
  - "snuba"
  - "consumer"
  - "--storage"
  - "outcomes_raw"
  - "--auto-offset-reset"
  - "{{ .Values.snuba.outcomesConsumer.autoOffsetReset }}"
  - "--max-batch-size"
  - "{{ default "3" .Values.snuba.outcomesConsumer.maxBatchSize }}"
  {{- if .Values.snuba.outcomesConsumer.processes }}
  - "--processes"
  - "{{ .Values.snuba.outcomesConsumer.processes }}"
  {{- end }}
  {{- if .Values.snuba.outcomesConsumer.inputBlockSize }}
  - "--input-block-size"
  - "{{ .Values.snuba.outcomesConsumer.inputBlockSize }}"
  {{- end }}
  {{- if .Values.snuba.outcomesConsumer.outputBlockSize }}
  - "--output-block-size"
  - "{{ .Values.snuba.outcomesConsumer.outputBlockSize }}"
  {{- end }}
  {{- if .Values.snuba.outcomesConsumer.maxBatchTimeMs }}
  - "--max-batch-time-ms"
  - "{{ .Values.snuba.outcomesConsumer.maxBatchTimeMs }}"
  {{- end }}
  {{- if .Values.snuba.outcomesConsumer.queuedMaxMessagesKbytes }}
  - "--queued-max-messages-kbytes"
  - "{{ .Values.snuba.outcomesConsumer.queuedMaxMessagesKbytes }}"
  {{- end }}
  {{- if .Values.snuba.outcomesConsumer.queuedMinMessages }}
  - "--queued-min-messages"
  - "{{ .Values.snuba.outcomesConsumer.queuedMinMessages }}"
  {{- end }}
  {{- if .Values.snuba.outcomesConsumer.noStrictOffsetReset }}
  - "--no-strict-offset-reset"
  {{- end }}
{{- end -}}
{{- $container := include "snuba.outcomesConsumer.container" . }}
{{- include "snuba.spec" (list . .Values.snuba.outcomesConsumer "outcomes-consumer" $container) }}
