apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-snuba-replacer
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "18"
  {{- end }}
{{- define "snuba.replacer.container" -}}
command:
  - "snuba"
  - "replacer"
  - "--storage"
  - "errors"
  - "--auto-offset-reset"
  - "{{ .Values.snuba.replacer.autoOffsetReset }}"
  {{- if .Values.snuba.replacer.maxBatchTimeMs }}
  - "--max-batch-time-ms"
  - "{{ .Values.snuba.replacer.maxBatchTimeMs }}"
  {{- end }}
  {{- if .Values.snuba.replacer.queuedMaxMessagesKbytes }}
  - "--queued-max-messages-kbytes"
  - "{{ .Values.snuba.replacer.queuedMaxMessagesKbytes }}"
  {{- end }}
  {{- if .Values.snuba.replacer.queuedMinMessages }}
  - "--queued-min-messages"
  - "{{ .Values.snuba.replacer.queuedMinMessages }}"
  {{- end }}
{{- end -}}
{{- $container := include "snuba.replacer.container" . }}
{{- include "snuba.spec" (list . .Values.snuba.replacer "replacer" $container) }}