apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-sessions-consumer
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "16"
  {{- end }}
{{- define "snuba.sessionsConsumer.container" -}}
command:
  - "snuba"
  - "consumer"
  - "--storage"
  - "sessions_raw"
  - "--auto-offset-reset"
  - "{{ .Values.snuba.sessionsConsumer.autoOffsetReset }}"
  - "--max-batch-time-ms"
  - "750"
  {{- if .Values.snuba.sessionsConsumer.maxBatchSize }}
  - "--max-batch-size"
  - "{{ .Values.snuba.sessionsConsumer.maxBatchSize }}"
  {{- end }}
  {{- if .Values.snuba.sessionsConsumer.processes }}
  - "--processes"
  - "{{ .Values.snuba.sessionsConsumer.processes }}"
  {{- end }}
  {{- if .Values.snuba.sessionsConsumer.inputBlockSize }}
  - "--input-block-size"
  - "{{ .Values.snuba.sessionsConsumer.inputBlockSize }}"
  {{- end }}
  {{- if .Values.snuba.sessionsConsumer.outputBlockSize }}
  - "--output-block-size"
  - "{{ .Values.snuba.sessionsConsumer.outputBlockSize }}"
  {{- end }}
  {{- if .Values.snuba.sessionsConsumer.maxBatchTimeMs }}
  - "--max-batch-time-ms"
  - "{{ .Values.snuba.sessionsConsumer.maxBatchTimeMs }}"
  {{- end }}
  {{- if .Values.snuba.sessionsConsumer.queuedMaxMessagesKbytes }}
  - "--queued-max-messages-kbytes"
  - "{{ .Values.snuba.sessionsConsumer.queuedMaxMessagesKbytes }}"
  {{- end }}
  {{- if .Values.snuba.sessionsConsumer.queuedMinMessages }}
  - "--queued-min-messages"
  - "{{ .Values.snuba.sessionsConsumer.queuedMinMessages }}"
  {{- end }}
  {{- if .Values.snuba.sessionsConsumer.noStrictOffsetReset }}
  - "--no-strict-offset-reset"
  {{- end }}
{{- end -}}
{{- $container := include "snuba.sessionsConsumer.container" . }}
{{- include "snuba.spec" (list . .Values.snuba.sessionsConsumer "sessions-consumer" $container) }}
