apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-snuba-replays-consumer
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "12"
  {{- end }}
{{- define "snuba.replaysConsumer.container" -}}
command:
  - "snuba"
  - "consumer"
  - "--storage"
  - "replays"
  - "--consumer-group"
  - "replays_group"
  - "--auto-offset-reset"
  - "{{ .Values.snuba.replaysConsumer.autoOffsetReset }}"
  - "--max-batch-time-ms"
  - "750"
  {{- if .Values.snuba.replaysConsumer.maxBatchSize }}
  - "--max-batch-size"
  - "{{ .Values.snuba.replaysConsumer.maxBatchSize }}"
  {{- end }}
  {{- if .Values.snuba.replaysConsumer.processes }}
  - "--processes"
  - "{{ .Values.snuba.replaysConsumer.processes }}"
  {{- end }}
  {{- if .Values.snuba.replaysConsumer.inputBlockSize }}
  - "--input-block-size"
  - "{{ .Values.snuba.replaysConsumer.inputBlockSize }}"
  {{- end }}
  {{- if .Values.snuba.replaysConsumer.outputBlockSize }}
  - "--output-block-size"
  - "{{ .Values.snuba.replaysConsumer.outputBlockSize }}"
  {{- end }}
  {{- if .Values.snuba.replaysConsumer.maxBatchTimeMs }}
  - "--max-batch-time-ms"
  - "{{ .Values.snuba.replaysConsumer.maxBatchTimeMs }}"
  {{- end }}
  {{- if .Values.snuba.replaysConsumer.queuedMaxMessagesKbytes }}
  - "--queued-max-messages-kbytes"
  - "{{ .Values.snuba.replaysConsumer.queuedMaxMessagesKbytes }}"
  {{- end }}
  {{- if .Values.snuba.replaysConsumer.queuedMinMessages }}
  - "--queued-min-messages"
  - "{{ .Values.snuba.replaysConsumer.queuedMinMessages }}"
  {{- end }}
  {{- if .Values.snuba.replaysConsumer.noStrictOffsetReset }}
  - "--no-strict-offset-reset"
  {{- end }}
{{- end -}}
{{- $container := include "snuba.replaysConsumer.container" . }}
{{- include "snuba.spec" (list . .Values.snuba.replaysConsumer "replays-consumer" $container) }}
